doc

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -30,6 +30,20 @@ jobs:
       - name: Documentation
         run: python -m sphinx ./_doc ./dist/html -n
 
+      - name: Check Documentation Output
+        if: steps.documentation.outputs.documentationOutput != 'Hello, GitHub Actions!'
+        run: |
+          message="${{ steps.documentation.outputs.message }}"
+
+          if [[ $message == *"ERROR"* ]]; then
+            echo "Sphinx output has errors."
+            exit 1
+          fi
+          if [[ $message == *"WARNING"* ]]; then
+            echo "Sphinx output has warnings."
+            exit 1
+          fi
+
       - uses: actions/upload-artifact@v3
         with:
           path: ./dist/html/**
